swagger: '2.0'
info:
  title: MOVIES REST
  description: 'Node.js course'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /movies:
    get:
      tags:
        - movies
      summary: Get all movies
      x-swagger-router-controller: movies.search
      responses:
        '200':
          description: movie
          schema:
            $ref: '#/definitions/movie'

  /movies/{id}:
    get:
      tags:
        - movies
      summary: get movie by id
      x-swagger-router-controller: movies.search
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: movie
          schema:
            $ref: '#/definitions/movie'

  /movies/search:
    get:
      tags:
        - movies
      summary: get movie by title / add if no result
      x-swagger-router-controller: movies.search
      parameters:
        - name: title
          in: query
          required: true
          type: string
      responses:
        '200':
          description: movie
          schema:
            $ref: '#/definitions/movie'

  /movies/save:
    post:
      tags:
        - movies
      summary: add movie
      x-swagger-router-controller: movies.save
      parameters:
        - name: movie
          in: body
          required: true
          schema:
            $ref: '#/definitions/newmovie'
      responses:
        '200':
          description: movie
          schema:
            $ref: '#/definitions/movie'


definitions:
  movie:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      image:
        type: string
      imdbID:
        type: string
      year:
        type: string
  newmovie:
    type: object
    properties:
      name:
        type: string
      image:
        type: string
      imdbID:
        type: string
      year:
        type: string
